config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'home'    => 'static_pages#home'
  get 'new_workout' => 'workouts#new'
  get 'workouts' => 'workouts#index'

  root "static_pages#home"
  devise_for :users
  devise_scope :user do
  get "login", to: "devise/sessions#new"
  end
  resources :workouts do
    resources :exercises
  end
  

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :workout
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :workouts
end

app/models/workout.rb
class Workout < ActiveRecord::Base
	has_many :exercises, dependent: :destroy
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
	def create
		@workout = Workout.find(params[:workout_id])
		@exercise = @workout.exercises.create(params[:exercise].permit(:name, :sets, :reps, :weight))
		redirect_to workout_path(@workout)
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
	before_action :find_workout, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	
	def index
		# if
			@workouts = current_user.workouts
		# else
		# 	redirect_to new_user_session_path, notice: 'You are not logged in.'
		# end
	end

	def show
	end

	def new
		@workout = current_user.workouts.build
	end

	def create
		@workout = current_user.workouts.build(workout_params)
		if @workout.save
			redirect_to @workout
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @workout.update(workout_params)
			redirect_to @workout
		else
			render 'edit'
		end
	end

	def destroy
		@workout.destroy
		redirect_to root_path
	end

	private 

	def workout_params
		params.require(:workout).permit(:date, :workout, :mood, :length)
	end

	def find_workout
		# @workout = current_user.workouts
		@workout = current_user.workouts.find(params[:id])
		#@workout = Workout.find(params[:id])
		#Workout.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/_exercise.html.haml
%p= exercise.name
%p= exercise.sets
%p= exercise.reps
%p= exercise.weight

app/views/exercises/_form.html.haml
= simple_form_for([@workout, @workout.exercises.build]) do |f|
	= f.input :name, input_html: { class: "form-control" }
	= f.input :sets, input_html: { class: "form-control" }
	= f.input :reps, input_html: { class: "form-control" }
	= f.input :weight, input_html: { class: "form-control" }
	%br/
	= f.button :submit

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Workout Log App by Matthias Chia
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Workout Log", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <li><% if user_signed_in? %>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
            <% else %>
              <%= link_to('Login', new_user_session_path)  %>  
            <% end %>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Workout Log App </title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Workout Log App", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Help",   help_path %></li>
          </ul>
        </nav>
      </div>
    </header>
    <%= render 'layouts/header' %>
    <div class="container">
      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>
  This is an individual project for CIT 597 using Ruby on Rails to code an web app. It is a workout tracker app that helps you creates a workout and add exercises to each workout.
</p>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>
  Contact me at mchia2@gmail.com
</p>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>
  Welcome! This is my web app for workout log.
</p>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
<div class="center jumbotron">
  <h1>Welcome to the Workout Log</h1>
  <h2>
   This is an workout tracker that helps you log your workouts.
  </h2>
  <% if user_signed_in? %>
    <%= link_to('Edit registration', edit_user_registration_path, class: "btn btn-lg btn-primary") %>
    <%= link_to('New Workout', new_workout_path, class: "btn btn-lg btn-primary") %>
    <%= link_to('View Workouts', workouts_path, class: "btn btn-lg btn-primary") %>
  <% else %>
    <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
  <% end %>

</html>

app/views/workouts/_form.html.erb
<%= simple_form_for(@workout, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.input :date, label: "Date" %>
  <%= f.input :workout, label: "Body Part", input_html: { class: "form-control" } %>
  <%= f.input :mood, label: "How're you feeling?", input_html: {class: "form-control"} %>
  <%= f.input :length, label: "How long was the workout?", input_html: {class: "form-control"} %>
  <%= f.submit ( f.object.new_record? ? "Create" : "Update"), class: "btn" %>
  
<% end %>

app/views/workouts/edit.html.haml
%h1 Edit Workout

= render 'form'

= link_to "Cancel", root_path

app/views/workouts/index.html.erb
<html>
  <%if @workouts.empty? %>
    <p> No workouts yet! </p>
    <p> <%= link_to "Create new workout", new_workout_path, class: "btn btn-lg btn-primary" %>
  <% else %>
    <% @workouts.each do |workout| %>
    	<% if workout.user = current_user %>
      		<p> <%= link_to workout.date.strftime("%A %B %e"), workout %> </p>
      		<p> <%= workout.workout %> </p>
      	<% else %>
      		<p> You have no authorization to view this! </p>
    	<% end %>
      <% end %>
  <% end %>

</html>

app/views/workouts/new.html.haml
%h1 New Workout

= render 'form'

= link_to "Cancel", root_path

app/views/workouts/show.html.erb
<html>
	
	<h3 align= "left"> <%= @workout.date %> </h3>
    <p> <%= @workout.workout %> </p>
    <p> <%= @workout.mood %></p>
    <p> <%= @workout.length %></p>

    <h3 align= "left"> Exercises </h3>
    <%= render @workout.exercises %>
    <h4 alignn= "left"> Add an exercise </h4>
    <%= render "exercises/form" %>
    <%= link_to "Back", root_path %> 
    <%= link_to "Edit", edit_workout_path(@workout) %>
    <%= link_to "Delete", workout_path(@workout), method: :delete, data: { confirm: "Are you sure?"} %>
		
</html>